---
- hosts: localhost
  connection: local

  vars_files:
    - vars/common.yml
    - "vars/{{ lookup('env', 'AS_CONFIG') }}.yml"

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    - include_tasks: tasks/remove.yml

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    - name: Get pacman keys
      command: pacman-key --list-sigs
      changed_when: false
      register: pacman_keys

    - include_tasks: tasks/sudo.yml
    - include_tasks: tasks/pacman.yml
    - include_tasks: tasks/aur.yml
    - include_tasks: tasks/kernel.yml
    - include_tasks: tasks/bootloader.yml
    - include_tasks: tasks/network.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ntp.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/xorg.yml
    - include_tasks: tasks/blacklist-pc-speaker.yml
    - include_tasks: tasks/desktop.yml
    - include_tasks: tasks/basic-tools.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/timers.yml
      with_items:
        - clean-cache
    - include_tasks: tasks/systemd.yml
    - include_tasks: tasks/email.yml
      when: not minimal
    - include_tasks: tasks/media.yml
      when: not minimal
    - include_tasks: tasks/chinese.yml
      when: not minimal
    - include_tasks: tasks/sysctl.yml
    - include_tasks: tasks/dotfiles.yml user={{ user_item }}
      with_items: '{{ users_inc_super }}'
      loop_control:
        loop_var: user_item
    - include_tasks: tasks/rbenv.yml user={{ user_item }}
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include_tasks: tasks/pyenv.yml user={{ user_item }}
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include_tasks: tasks/ndenv.yml user={{ user_item }}
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include_tasks: tasks/plenv.yml user={{ user_item }}
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include_tasks: tasks/shared.yml
      when: model == "VirtualBox"
    - include_tasks: tasks/pkgfile.yml
    - include_tasks: tasks/vostro-tools.yml
      when: model == "Vostro 3700"
    - include_tasks: tasks/udev.yml
    - include_tasks: tasks/printing.yml
      when: model != "VirtualBox"
    - include_tasks: tasks/sound.yml
    - include_tasks: tasks/chef.yml user={{ user_item }}
      when: long_bit.stdout == "64" and install_chef
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include_tasks: tasks/power.yml
      when: laptop
    - include_tasks: tasks/debugging.yml
      when: not minimal
    - include_tasks: tasks/openvpn.yml
      when: not minimal
    - include_tasks: tasks/tex.yml
      when: not minimal
    - include_tasks: tasks/locale.yml
    - include_tasks: tasks/wine.yml
      when: not minimal
    - include_tasks: tasks/postremove.yml

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
