---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: config_file
      prompt: "Which vars should I load?"
      private: no

  vars_files:
    - vars/common.yml
    - vars/{{ config_file }}.yml

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    - include: tasks/remove.yml

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    - include: tasks/pacman.yml
    - include: tasks/bootloader.yml
      when: model != "rpi"
    - include: tasks/network.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/users.yml
    - include: tasks/aur.yml
    - include: tasks/sudo.yml
    - include: tasks/ntp.yml
    - include: tasks/fonts.yml
      when: model != "rpi"
    - include: tasks/xorg.yml
      when: model != "rpi"
    - include: tasks/blacklist-pc-speaker.yml
      when: model != "rpi"
    - include: tasks/desktop.yml
      when: model != "rpi"
    - include: tasks/basic-tools.yml
    - include: tasks/cron.yml
    - include: tasks/systemd.yml
    - include: tasks/email.yml
      when: model != "rpi"
    - include: tasks/media.yml
      when: model != "rpi"
    - include: tasks/chinese.yml
      when: model != "rpi"
    - include: tasks/sysctl.yml
    - include: tasks/dotfiles.yml user={{ user_item }}
      with_items: '{{ users_inc_super }}'
      loop_control:
        loop_var: user_item
    - include: tasks/rbenv.yml user={{ user_item }}
      when: model != "rpi"
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include: tasks/pyenv.yml user={{ user_item }}
      when: model != "rpi"
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include: tasks/ndenv.yml user={{ user_item }}
      when: model != "rpi"
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include: tasks/plenv.yml user={{ user_item }}
      when: model != "rpi"
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include: tasks/shared.yml
      when: model == "VirtualBox"
    - include: tasks/pkgfile.yml
    - include: tasks/vostro-tools.yml
      when: model == "Vostro 3700"
    - include: tasks/lin-dev.yml
      when: install_lin_dev
    - include: tasks/udev.yml
      when: model != "rpi"
    - include: tasks/printing.yml
      when: model != "rpi"
    - include: tasks/sound.yml
      when: model != "rpi"
    - include: tasks/chef.yml user={{ user_item }}
      when: 'model != "rpi" and long_bit.stdout == "64"'
      with_items: '{{ install_env_users }}'
      loop_control:
        loop_var: user_item
    - include: tasks/skype.yml
      when: 'model != "rpi" and long_bit.stdout == "64"'
    - include: tasks/power.yml
      when: laptop
    - include: tasks/debugging.yml
    - include: tasks/locale.yml
