---
- name: Install tools that don't require Ansible configuration (all)
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - rsync
    - tmux
    - git
    - openssh
    - htop
    - mupdf
    - btrfs-progs
    - atop
    - wmname

- name: Install tools that don't require Ansible configuration (Chris specific)
  pacman: name={{ item }} state=present
  when: not minimal
  with_items:
    - macchanger
    - python-virtualenvwrapper
    - bind-tools
    - lsof
    - whois
    - zenity  # used for trello-popup
    - dhclient  # wtf? without this ipv6 wired profiles seem to bomb
    - reflector
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - zstd
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - openconnect
    - mupdf-tools  # `mutool clean` to fix pdfs
    - msmtp
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - irssi
    # For duply
    - python2-boto
    - parallel
    - pdfpc
    - enca
    - android-tools
    - android-udev
    - hugin
    - gimp
    - gimp-plugin-gmic
    - gmic
    - rust
    - dmidecode  # certsign
    - imagemagick
    - ghostscript # for imagemagick
    - mpv
    - chromium
    - ncdu
    - powertop
    - openbox  # presentations
    - libreoffice-still
    - mktorrent
    - mpd
    - mpc

- name: Install basic tools requiring aur (Chris specific)
  aur: name={{ item }}
  when: not minimal
  with_items:
    - cconv
    - duply
    - drive
    - shellcheck
    - docx2txt
    - antiword
    - pngquant
    - sshrc
    - spotify
    - udftools
    - xinput-toggle
    - nota
    - pandoc-bin
    - mpdscribble
    - mpdmenu
  become: yes
  become_user: makepkg

- name: Install bluejeans on 64-bit only
  aur: name=bluejeans
  become: yes
  become_user: makepkg
  when: long_bit.stdout == "64" and not minimal

- name: Install laptop tools
  aur: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg
