---
- name: Install tools that don't require Ansible configuration
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - rsync
    - tmux
    - macchanger
    - python-virtualenvwrapper
    - bind-tools
    - git
    - lsof
    - whois
    - strace
    - atop
    - zenity  # used for trello-popup
    - openssh
    - htop
    - dhclient  # wtf? without this ipv6 wired profiles seem to bomb
    - autossh
    - ncdu
    - acpi
    - acpid
    - reflector
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - evince
    - zstd
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - colordiff
    - dosfstools
    - openconnect
    - mupdf
    - mupdf-tools  # `mutool clean` to fix pdfs
    - msmtp
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - gnome-icon-theme
    - irssi
    # For duply
    - python2-boto
    - pinta
    - parallel
    # Video game gamma
    - xorg-xgamma
    - pdfpc
    - okular  # sometimes lpr fails to print stuff, where okular works... :-/
    - abs
    - enca

- name: Check Tor Browser Bundle key's existence
  command: gpg --list-keys 2E1AC68ED40814E0
  changed_when: false
  ignore_errors: true
  register: tor_key
  become: yes
  become_user: makepkg

- name: Set up GPG key for Tor Browser Bundle developers
  command: gpg --keyserver pgp.mit.edu --recv-keys 2E1AC68ED40814E0
  when: tor_key.rc != 0
  become: yes
  become_user: makepkg
  retries: 3
  delay: 1

- name: Install basic tools requiring aur
  aur: name={{ item }}
  with_items:
    - duply
    - drive
    - xbanish
    - clipmenu
    - shellcheck
    - docx2txt
    - antiword
    - pngquant
    - sshrc
    - spotify
    - urlscan
    - udftools
    - xinput-toggle
    - gvfs-mtp
    - tor-browser-en
    - nota
    - frogr
    - wdiff
    - cconv
  become: yes
  become_user: makepkg

- name: Install bluejeans on 64-bit only
  aur: name=bluejeans
  become: yes
  become_user: makepkg
  when: long_bit.stdout == "64"

- name: Install laptop tools
  aur: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg

- name: Start acpid
  service: name=acpid state=started enabled=yes
