---
- name: Install tools that don't require Ansible configuration
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - mercurial
    - rsync
    - notmuch
    - notmuch-mutt
    - tmux
    - python-virtualenvwrapper
    - gnome-icon-theme
    - irssi
    # For duply
    - python2-boto
    # For irssi scripts
    - perl-datetime
    # For photo backups
    - perl-image-exiftool
    - aspell
    - pinta
    - android-tools
    - android-udev
    - atop
    - htop
    - bind-tools
    - nmap
    - git
    - lsof
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - whois
    - libjpeg-turbo  # for jpegtran
    - msmtp
    - ctags
    - ltrace
    - strace
    - fuse-exfat
    - dosfstools
    - perf

- name: Set up GPG key for Tor Browser Bundle developers
  command: gpg --keyserver pgp.mit.edu --recv-keys 2E1AC68ED40814E0
  become: yes
  become_user: makepkg

- name: Install basic tools requiring yaourt
  yaourt: name={{ item }}
  with_items:
    - duply
    - pdftk-bin
    - drive
    - xbanish
    - clipmenu
    - shellcheck
    - docx2txt
    - pngquant
    - tor-browser-en
  become: yes
  become_user: makepkg

- name: Install laptop tools
  yaourt: name={{ item }}
  with_items:
    - acpi
    - acpid
    - bats
  when: laptop

- name: Enable atop logging
  service: name=atop state=started enabled=yes
