---
- name: Install tools that don't require Ansible configuration
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - p7zip
    - mercurial
    - rsync
    - tmux
    - python-virtualenvwrapper
    - gnome-icon-theme
    - irssi
    # For duply
    - python2-boto
    # For irssi scripts
    - perl-datetime
    # For photo backups
    - perl-image-exiftool
    - aspell
    - pinta
    - android-tools
    - android-udev
    - atop
    - htop
    - bind-tools
    - nmap
    - git
    - lsof
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - whois
    - libjpeg-turbo  # for jpegtran

- name: Install basic tools requiring yaourt
  yaourt: name={{ item }}
  with_items:
    - duply
    - pdftk-bin
    - drive
    - xbanish
    - clipmenu
    - shellcheck
    - docx2txt
  sudo: yes
  sudo_user: makepkg

- name: Install laptop tools
  pacman: name=acpi state=present
  when: laptop
