---
- name: Install tools that don't require Ansible configuration (all)
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - rsync
    - tmux
    - git
    - openssh
    - htop
    - mupdf
    - btrfs-progs

- name: Install tools that don't require Ansible configuration (Chris specific)
  pacman: name={{ item }} state=present
  when: not minimal
  with_items:
    - macchanger
    - python-virtualenvwrapper
    - bind-tools
    - lsof
    - whois
    - atop
    - zenity  # used for trello-popup
    - dhclient  # wtf? without this ipv6 wired profiles seem to bomb
    - ncdu
    - reflector
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - zstd
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - colordiff
    - dosfstools
    - openconnect
    - mupdf-tools  # `mutool clean` to fix pdfs
    - msmtp
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - irssi
    # For duply
    - python2-boto
    - pinta
    - parallel
    - pdfpc
    - enca
    - lshw
    - android-tools
    - android-udev
    - hugin
    - gthumb
    - gimp
    - gimp-plugin-gmic
    - gmic
    - rust
    - chromium
    - libreoffice-fresh
    - dmidecode  # certsign
    - xautolock
    - xorg-xwininfo  # lock-maybe
    - imagemagick
    - ghostscript # for imagemagick
    - mpv

- name: Check Matt Caswell's key's existence (libopenssl-1.0-compat)
  command: gpg --list-keys D9C4D26D0E604491
  changed_when: false
  ignore_errors: true
  register: openssl_compat_key
  become: yes
  become_user: makepkg

- name: Set up GPG key for Matt Caswell (libopenssl-1.0-compat)
  command: gpg --keyserver pgp.mit.edu --recv-keys D9C4D26D0E604491
  when: openssl_compat_key.rc != 0
  become: yes
  become_user: makepkg
  retries: 3
  delay: 1

- name: Check curl's key's existence (libopenssl-1.0-compat)
  command: gpg --list-keys 5CC908FDB71E12C2
  changed_when: false
  ignore_errors: true
  register: curl_key
  become: yes
  become_user: makepkg

- name: Set up GPG key for curl (libopenssl-1.0-compat)
  command: gpg --keyserver pgp.mit.edu --recv-keys 5CC908FDB71E12C2
  when: curl_key.rc != 0
  become: yes
  become_user: makepkg
  retries: 3
  delay: 1

- name: Install basic tools requiring aur (Chris specific)
  aur: name={{ item }}
  when: not minimal
  with_items:
    - duply
    - drive
    - xbanish
    - shellcheck
    - docx2txt
    - antiword
    - pngquant
    - sshrc
    - spotify
    - udftools
    - xinput-toggle
    - nota
    - pandoc-bin
  become: yes
  become_user: makepkg

- name: Install bluejeans on 64-bit only
  aur: name=bluejeans
  become: yes
  become_user: makepkg
  when: long_bit.stdout == "64" and not minimal

- name: Install laptop tools
  aur: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg
