---
# No way to handle conflicts nicely, sadly
- name: Remove gcc in preparation for gcc multilib
  pacman: name={{ item }} state=absent force=yes
  with_items:
    - gcc
    - gcc-libs

- name: Install gcc-multilib
  pacman: name=gcc-multilib state=present

- name: Install tools that don't require Ansible configuration
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - rsync
    - tmux
    - macchanger
    - python-virtualenvwrapper
    - bind-tools
    - git
    - lsof
    - whois
    - strace
    - atop
    - zenity  # used for trello-popup
    - openssh
    - htop
    - dhclient  # wtf? without this ipv6 wired profiles seem to bomb

- name: Install non-RPi basic tools
  pacman: name={{ item }} state=present
  when: model != "rpi"
  with_items:
    - reflector
    - linux-lts
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - evince
    - zstd
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - colordiff
    - dosfstools
    - openconnect
    - mupdf
    - msmtp
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - gnome-icon-theme
    - irssi
    # For duply
    - python2-boto
    # For irssi scripts
    - perl-datetime
    # For photo backup renaming
    - perl-image-exiftool
    - pinta

- name: Set up GPG key for Tor Browser Bundle developers
  command: gpg --keyserver pgp.mit.edu --recv-keys 2E1AC68ED40814E0
  become: yes
  become_user: makepkg

- name: Install basic tools requiring yaourt
  yaourt: name={{ item }}
  with_items:
    - bcc-tools
  become: yes
  become_user: makepkg

- name: Install non-RPi basic tools requiring yaourt
  yaourt: name={{ item }}
  when: model != 'rpi'
  with_items:
    - duply
    - drive
    - xbanish
    - clipmenu
    - shellcheck
    - docx2txt
    - antiword
    - pngquant
    - sshrc
    - bluejeans
    - spotify
    - urlscan
    - udftools
    - xinput-toggle
    - simple-mtpfs
    - tor-browser-en
    - nota
    - frogr
  become: yes
  become_user: makepkg

- name: Install laptop tools
  yaourt: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg
