---
- name: Install tools that don't require Ansible configuration
  pacman: name={{ item }} state=present
  with_items:
    - vim
    - rsync
    - tmux
    - macchanger
    - python-virtualenvwrapper
    - bind-tools
    - git
    - lsof
    - whois
    - atop
    - zenity  # used for trello-popup
    - openssh
    - htop
    - dhclient  # wtf? without this ipv6 wired profiles seem to bomb
    - autossh
    - ncdu
    - acpi
    - acpid
    - reflector
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - evince
    - zstd
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - colordiff
    - dosfstools
    - openconnect
    - mupdf
    - mupdf-tools  # `mutool clean` to fix pdfs
    - msmtp
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - gnome-icon-theme
    - irssi
    # For duply
    - python2-boto
    - pinta
    - parallel
    - pdfpc
    - okular  # sometimes lpr fails to print stuff, where okular works... :-/
    - enca
    - lshw
    - android-tools
    - android-udev
    - hugin
    - gthumb
    - gimp
    - gimp-plugin-gmic
    - gmic
    - base
    - base-devel
    - pandoc-lite

- name: Check Tor Browser Bundle key's existence
  command: gpg --list-keys 2E1AC68ED40814E0
  changed_when: false
  ignore_errors: true
  register: tor_key
  become: yes
  become_user: makepkg

- name: Set up GPG key for Tor Browser Bundle developers
  command: gpg --keyserver pgp.mit.edu --recv-keys 2E1AC68ED40814E0
  when: tor_key.rc != 0
  become: yes
  become_user: makepkg
  retries: 3
  delay: 1

- name: Check Matt Caswell's key's existence (libopenssl-1.0-compat)
  command: gpg --list-keys D9C4D26D0E604491
  changed_when: false
  ignore_errors: true
  register: openssl_compat_key
  become: yes
  become_user: makepkg

- name: Set up GPG key for Matt Caswell (libopenssl-1.0-compat)
  command: gpg --keyserver pgp.mit.edu --recv-keys D9C4D26D0E604491
  when: openssl_compat_key.rc != 0
  become: yes
  become_user: makepkg
  retries: 3
  delay: 1

- name: Check curl's key's existence (libopenssl-1.0-compat)
  command: gpg --list-keys 5CC908FDB71E12C2
  changed_when: false
  ignore_errors: true
  register: curl_key
  become: yes
  become_user: makepkg

- name: Set up GPG key for curl (libopenssl-1.0-compat)
  command: gpg --keyserver pgp.mit.edu --recv-keys 5CC908FDB71E12C2
  when: curl_key.rc != 0
  become: yes
  become_user: makepkg
  retries: 3
  delay: 1

- name: Install basic tools requiring aur
  aur: name={{ item }}
  with_items:
    - duply
    - drive
    - xbanish
    - clipmenu
    - shellcheck
    - docx2txt
    - antiword
    - pngquant
    - sshrc
    - spotify
    - udftools
    - xinput-toggle
    - gvfs-mtp
    - tor-browser-en
    - nota
    - cconv
    - screenkey
    - xprintidle
    - prompter
  become: yes
  become_user: makepkg

- name: Install bluejeans on 64-bit only
  aur: name=bluejeans
  become: yes
  become_user: makepkg
  when: long_bit.stdout == "64"

- name: Install laptop tools
  aur: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg

- name: Start acpid
  service: name=acpid state=started enabled=yes
