---
# No way to handle conflicts nicely, sadly
- name: Remove gcc in preparation for gcc multilib
  pacman: name={{ item }} state=absent force=yes
  with_items:
    - gcc
    - gcc-libs

- name: Install gcc-multilib
  pacman: name=gcc-multilib state=present

- name: Install tools that don't require Ansible configuration
  pacman: name={{ item }} state=present
  with_items:
    - reflector
    - vim
    - p7zip
    - maim
    - slop  # optdepends for `screenshot --select`
    - rsync
    - notmuch
    - notmuch-mutt
    - tmux
    - macchanger
    - python-virtualenvwrapper
    - gnome-icon-theme
    - irssi
    # For duply
    - python2-boto
    # For irssi scripts
    - perl-datetime
    # For photo backup renaming
    - perl-image-exiftool
    - pinta
    - bind-tools
    - git
    - lsof
    - xclip
    - pass
    - pkgbuild-introspection
    - sxiv
    - whois
    - msmtp
    - strace
    - dosfstools
    - openconnect
    - mupdf
    - atop
    - mercurial  # needed for some pyenv installed stuff
    - flashplugin
    - colordiff
    - zenity  # used for trello-popup
    - openssh

- name: Install basic tools requiring yaourt
  yaourt: name={{ item }}
  with_items:
    - duply
    - drive
    - xbanish
    - clipmenu
    - shellcheck
    - docx2txt
    - pngquant
    - sshrc
    - bluejeans
    - spotify
    - urlscan
    - udftools
  become: yes
  become_user: makepkg

- name: Install laptop tools
  yaourt: name={{ item }}
  with_items:
    - bats
  when: laptop
  become: yes
  become_user: makepkg
