---
- name: Install Chef packages
  aur: name={{ item }}
  with_items:
    - chef-dk
    - vagrant
    - "{{ kernel }}-headers"  # needed for virtualbox-host-dkms
    - virtualbox
  become: yes
  become_user: makepkg

- name: Get list of Vagrant plugins installed
  shell: "vagrant plugin list | awk '{ print $1 }'"
  register: vagrant_plugins
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Vagrant plugins
  command: "vagrant plugin install {{ item }}"
  with_items:
    - vagrant-berkshelf
    - vagrant-omnibus
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item }}" not in vagrant_plugins.stdout_lines'
