---
- name: Install cronie
  pacman: name=cronie state=present

- name: Enable cronie
  service: name=cronie state=started enabled=yes

- name: Cron to download updates
  copy: src=files/cron/download-updates dest=/etc/cron.d/download-updates

- name: Cron to trim SSD
  copy: src=files/cron/fstrim dest=/etc/cron.d/fstrim
