---
- name: Install cronie
  pacman: name=cronie state=present

- name: Enable cronie
  service: name=cronie state=started enabled=yes

- name: Remove old crons
  file: path={{ item }} state=absent
  with_items:
    - /etc/cron.d/download-updates
    - /etc/cron.d/clean-cache
    - /etc/cron.d/fstrim
    - /etc/cron.d/i8kfan
    - /etc/cron.d/pkgfile
    - /etc/cron.d/purge-atop-logs
    - /etc/cron.d/reflector
