---
- name: Install debugging tools
  pacman: name={{ item }} state=present
  with_items:
    - atop
    - bind-tools
    - htop
    - iftop
    - mtr
    - nethogs
    - strace
    - tcpdump
    - nmap
    - logrotate  # for atop
    - powertop
    - wireshark-cli
    - mcelog
    - perf
    - time

- name: Install debugging tools (AUR)
  aur: name={{ item }}
  with_items:
    - bcc-tools
    - python2-bcc
  become: yes
  become_user: makepkg

- name: Copy atop config
  copy: src=files/atop.daily dest=/usr/share/atop/atop.daily mode=700

- name: Mask atop
  systemd: name=atop state=stopped enabled=no masked=yes
