---
- name: Install dwm
  yaourt: name=dwm-cdown-git
  become: yes
  become_user: makepkg

- name: Install desktop utilities
  pacman: name={{ item }} state=present
  with_items:
    - dmenu
    - imagemagick
    - ghostscript # for imagemagick
    - rxvt-unicode
    - slock
    - alsa-utils
    - libnotify
    - xfce4-notifyd

- name: Install unbranded Firefox (XPI signing, bleh)
  yaourt: name=firefox-unbranded-bin
  become: yes
  become_user: makepkg

- name: Install urxvt Perl extensions
  yaourt: name=urxvt-perls
  become: yes
  become_user: makepkg

- name: Set up terminal fonts
  pacman: name={{ item }}
  with_items:
    - terminus-font
    - ttf-inconsolata
    - ttf-symbola
