---
- name: Install dwm
  aur: name=dwm-cdown-git
  become: yes
  become_user: makepkg

- name: Install desktop utilities
  pacman: name={{ item }} state=present
  with_items:
    - dmenu
    - rxvt-unicode
    - slock

- name: Install optional desktop utilities
  pacman: name={{ item }} state=present
  with_items:
    - libnotify
    - xfce4-notifyd
  when: not minimal

- name: Install unbranded Firefox (XPI signing, bleh)
  aur: name=firefox-unbranded-bin
  become: yes
  become_user: makepkg

- name: Install urxvt Perl extensions
  aur: name=urxvt-perls
  when: not minimal
  become: yes
  become_user: makepkg

- name: Set up terminal fonts
  pacman: name={{ item }}
  with_items:
    - terminus-font
    - ttf-inconsolata
    - ttf-symbola

- name: Lock screen on suspend for cdown
  copy: src=files/slock.service dest=/etc/systemd/system/slock.service mode=644

- name: Enable lock service
  service: name=slock enabled=yes
