---
- name: Set up locale.conf
  copy: src=files/locale.conf dest=/etc/locale.conf
  register: locale_config

- name: Set up locale.gen
  copy: src=files/locale.gen dest=/etc/locale.gen
  register: locale_gen

- name: locale-gen
  command: locale-gen
  when: locale_config.changed or locale_gen.changed

- name: Install localepurge
  aur: name=localepurge

- name: Configure localepurge
  copy: src=files/locale.nopurge dest=/etc/locale.nopurge
