---
- name: Install media applications
  pacman: name={{ item }} state=present
  with_items:
    - mpv
    - mpd
    - mpc

- name: Install media applications requiring aur
  aur: name={{ item }}
  with_items:
    - mpdscribble
    - mpdmenu
  become: yes
  become_user: makepkg
