---
- name: Install nodenv
  aur: 'name={{ item }}'
  with_items:
    - nodenv
    - nodenv-node-build
  become: yes
  become_user: makepkg

- name: Get list of Nodes installed in nodenv
  shell: "nodenv versions | sed 's/^..//' | awk '{ print $1 }'"
  register: nodenv_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Nodes using nodenv
  shell: "nodenv install {{ item }} && nodenv global {{ item }}"
  with_items:
    - {{ node_version }}
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item }}" not in nodenv_versions.stdout_lines'

- name: Get list of installed packages
  shell: "eval \"$(nodenv init -)\" && npm ls -g | awk '$NF ~ /@/ { print $NF }' | awk -F@ '{ print $1 }'"
  register: nodenv_packages
  become: yes
  become_user: "{{ user }}"
  changed_when: false

#- name: Install node utilities
#  shell: 'eval "$(nodenv init -)" && npm install -g {{ item }} && nodenv rehash'
#  with_items:
#    - nativefier
#  become: yes
#  become_user: "{{ user }}"
#  when: '"{{ item | basename }}" not in nodenv_packages.stdout_lines'
