---
- name: Install wired tools
  pacman: name={{ item }} state=present
  with_items:
    - ifplugd

- name: Install wireless tools
  pacman: name={{ item }} state=present
  when: wifi
  with_items:
    - iw
    - wpa_supplicant
    - wireless_tools
    - dialog  # needed for wifi-menu
    - crda

- copy: src=files/wireless-regdom dest=/etc/conf.d/wireless-regdom

- copy: src=files/no-wifi-power-save dest=/etc/modprobe.d/no-wifi-power-save.conf

- template: src=files/hosts dest=/etc/hosts

- copy: src=files/bin/get-wired-interface dest=/usr/local/bin/get-wired-interface mode=755

- command: get-wired-interface
  register: wired_iface
  changed_when: false

- service: name=netctl-ifplugd@{{ wired_iface.stdout | trim }}
