---
- name: Automatically get DHCP lease
  service: name=dhcpcd state=started enabled=yes
  when: not wifi

- name: Install wireless tools
  pacman: name={{ item }} state=present
  when: wifi
  with_items:
    - wpa_supplicant
    - dialog  # needed for wifi-menu

- name: Install wireless tools
  pacman: name=wpa_supplicant state=present
  when: wifi
