---
- name: Disable old dhcpcd setup (now using netctl)
  service: name=dhcpcd state=stopped enabled=no

- name: Install wireless tools
  pacman: name={{ item }} state=present
  when: wifi
  with_items:
    - wpa_supplicant
    - dialog  # needed for wifi-menu

- name: Install wireless tools
  pacman: name=wpa_supplicant state=present
  when: wifi
