---
- name: Disable old dhcpcd setup (now using netctl)
  service: name=dhcpcd state=stopped enabled=no
  when: wifi

- name: Enable dhcpcd if not a wifi machine
  service: name=dhcpcd state=started enabled=yes
  when: not wifi

- name: Install wireless tools
  pacman: name={{ item }} state=present
  when: wifi
  with_items:
    - iw
    - wpa_supplicant
    - wireless_tools
    - dialog  # needed for wifi-menu

- copy: src=files/no-wifi-power-save dest=/etc/modules-load.d/no-wifi-power-save.conf

- template: src=files/hosts dest=/etc/hosts
