---
- name: Install aria2
  pacman: name=aria2 state=present

- name: Get pacman keys
  command: pacman-key --list-sigs
  changed_when: false
  register: pacman_keys

- name: Retrieve repo-ck key
  command: pacman-key -r 5EE46C4C
  register: retrieve_ck_key
  when: '"88A032865EE46C4C" not in pacman_keys.stdout'

- name: Lsign repo-ck key
  command: pacman-key --lsign-key 5EE46C4C
  when: retrieve_ck_key.changed

- name: Copy pacman configuration
  template: src=files/pacman.conf dest=/etc/pacman.conf
  when: model != 'rpi'

- name: Copy pacman configuration for RPi
  copy: src=files/pacman-arm.conf dest=/etc/pacman.conf
  when: model == 'rpi'

- name: Update package lists
  pacman: update_cache=yes
  changed_when: false
