---
- name: Copy pacman configuration
  template: src=files/pacman.conf dest=/etc/pacman.conf
  when: model != 'rpi'

- name: Copy pacman configuration for RPi
  copy: src=files/pacman-arm.conf dest=/etc/pacman.conf
  when: model == 'rpi'

- name: Update package lists
  pacman: update_cache=yes
  changed_when: false
