---
- name: Copy {{ item }} script
  copy: src=files/bin/{{ item }} dest=/usr/local/bin/{{ item }} mode=755
  with_items:
    - powerdown
    - powerup

- name: Install {{ item }} service
  copy: src=files/{{ item }}.service dest=/etc/systemd/system/{{ item }}.service mode=644
  with_items:
    - powerdown
    - powerup

- name: Enable {{ item }} service
  systemd: name={{ item }} enabled=yes daemon_reload=yes
  with_items:
    - powerdown
    - powerup

- name: Copy power targets udev rule
  copy: src=files/udev/powertargets.rules dest=/etc/udev/rules.d/99-powertargets.rules

- name: Copy power targets
  copy: src=files/{{ item }}.target dest=/etc/systemd/system
  with_items:
    - ac
    - battery

- name: Install ethtool for powerdown
  pacman: name=ethtool state=present

- name: Blacklist Bluetooth
  kernel_blacklist: name={{ item }} state=present
  with_items:
    - btusb
    - bluetooth
