---
- name: Install pyenv
  yaourt: name=pyenv
  sudo: yes
  sudo_user: makepkg

- name: Get list of Pythons installed in pyenv
  command: pyenv versions
  register: pyenv_versions
  sudo: yes
  sudo_user: "{{ user }}"
  changed_when: false

- name: Install Pythons using pyenv
  command: "pyenv install {{ item }}"
  with_items:
    - 3.5.0
  sudo: yes
  sudo_user: "{{ user }}"
  when: '"{{ item }}" not in pyenv_versions.stdout'
