---
- name: Install pyenv
  yaourt: name=pyenv
  become: yes
  become_user: makepkg

- name: Get list of Pythons installed in pyenv
  command: pyenv versions
  register: pyenv_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Pythons using pyenv
  command: "pyenv install {{ item }}"
  with_items:
    - 2.7.10
    - 3.5.0
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item }}" not in pyenv_versions.stdout'

- name: Install Python 3 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell 3.5.0 && pip install {{ item }}'
  with_items:
    - yturl
    - tzupdate
    - virtualenv
    - virtualenvwrapper
    - hg+https://bitbucket.org/logilab/astroid
    - hg+https://bitbucket.org/logilab/pylint
    - twine
    - ipython
    - flake8
    - line_profiler
    - memory_profiler
    - psutil
    - awscli
  become: yes
  become_user: "{{ user }}"

- name: Install Python 2 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell 2.7.10 && pip install {{ item }}'
  with_items:
    - gsutil
  become: yes
  become_user: "{{ user }}"
