---
- name: Install pyenv
  yaourt: name=pyenv
  become: yes
  become_user: makepkg

- name: Get list of Pythons installed in pyenv
  command: pyenv versions
  register: pyenv_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Pythons using pyenv
  command: "pyenv install {{ item }}"
  with_items:
    - 2.7.13
    - 3.6
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item }}" not in pyenv_versions.stdout'

- name: Get list of Python 3 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell 3.6 && pip freeze | awk -F= '{ print $1 }'"
  register: py3_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Get list of Python 2 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell 2.7.13 && pip freeze | awk -F= '{ print $1 }'"
  register: py2_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Python 3 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell 3.6 && pip install {{ item }}'
  with_items:
    - yturl
    - tzupdate
    - virtualenv
    - virtualenvwrapper
    - astroid
    - pylint
    - twine
    - ipython
    - flake8
    - line-profiler
    - memory-profiler
    - psutil
    - awscli
    - tox
    - pipdeptree
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item | basename }}" not in py3_utils.stdout_lines'

- name: Install Python 2 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell 2.7.13 && pip install {{ item }}'
  with_items:
    - gsutil
    - s3cmd
    - pipdeptree
    - stapler
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item | basename }}" not in py2_utils.stdout_lines'
