---
- name: Install rbenv
  aur: 'name={{ item }}'
  with_items:
    - rbenv
    - ruby-build
  become: yes
  become_user: makepkg

- name: Get list of Rubies installed in rbenv
  shell: "rbenv versions | sed 's/^..//' | awk '{ print $1 }'"
  register: rbenv_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Rubies using rbenv
  shell: "rbenv install {{ item }} && rbenv global {{ item }}"
  with_items:
    - 2.4.0
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item }}" not in rbenv_versions.stdout_lines'

- name: Get list of installed gems
  shell: "eval \"$(rbenv init -)\" && gem list | awk '{ print $1 }'"
  register: rbenv_gems
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Ruby utilities
  shell: 'eval "$(rbenv init -)" && gem install {{ item }} && rbenv rehash'
  with_items:
    - bundler
    - trello_cli
    - pomo
    - libnotify  # https://github.com/tj/pomo/issues/47
    - travis
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item | basename }}" not in rbenv_gems.stdout_lines'
