---
- name: Remove tools that are no longer used
  pacman: name={{ item }} state=absent
  with_items:
    - acpi
    - acpid
    - android-tools
    - android-udev
    - netatop  # Must be before atop
    - bcc-tools
    - ctags
    - emojione-color-font
    - exfat-utils
    - htop
    - lib32-apulse
    - logrotate
    - ltrace
    - mercurial
    - nmap
    - pdftk-bin
    - perf
    - skype
    - spotify
    - tor-browser-en
    - pngquant
    - ndenv
    - node-build

- name: Remove files that are no longer used
  file: path={{ item }} state=absent
  with_items:
    - /etc/modules-load.d/netatop.conf
    # wtf, why does the atop package force this midnight restart upon you by
    # default without checking if the service is enabled
    - /etc/cron.d/atop

- name: Disable services that are not used
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - atop
