---
- name: Remove tools that are no longer used
  pacman: name={{ item }} state=absent
  with_items:
    - ctags
    - emojione-color-font
    - exfat-utils
    - lib32-apulse
    - ltrace
    - pdftk-bin
    - skype
    - ndenv
    - node-build
    - pkgfile
    - xf86-video-intel  # we always use KMS
    - openvpn-update-resolv-conf  # now managed by ansible directly
    - youtube-dl  # done through pyenv
    - frogr
    - wdiff
    - urlscan
    - xorg-xgamma
    - laptop-mode
    - docker
    - netatop-dkms
    - netatop

- name: Remove unused files
  file: path={{ item }} state=absent
  with_items:
    - /etc/udev/rules.d/99-deadline-for-ssd.rules
    - /etc/cron.d/clear-corrupt-journals
    - /etc/modprobe.d/99-i915.conf
