---
- name: Remove tools that are no longer used
  pacman: name={{ item }} state=absent
  with_items:
    - acpi
    - acpid
    - android-tools
    - android-udev
    - netatop  # Must be before atop
    - ctags
    - emojione-color-font
    - exfat-utils
    - lib32-apulse
    - ltrace
    - nmap
    - pdftk-bin
    - perf
    - skype
    - ndenv
    - node-build

- name: Remove files that are no longer used
  file: path={{ item }} state=absent
  with_items:
    - /etc/modules-load.d/netatop.conf
