---
- name: Remove tools that are no longer used
  pacman: name={{ item }} state=absent
  with_items:
    - acpi
    - acpid
    - android-tools
    - android-udev
    - ctags
    - emojione-color-font
    - exfat-utils
    - lib32-apulse
    - ltrace
    - pdftk-bin
    - perf
    - skype
    - ndenv
    - node-build
    - pkgfile

- name: Remove unused files
  file: path={{ item }} state=absent
  with_items:
    - /etc/udev/rules.d/99-deadline-for-ssd.rules
