---
- name: Disable and stop {{ rem_timer }} timer
  systemd: name={{ rem_timer }}.timer state=stopped enabled=False

- name: Delete {{ rem_timer }} service and timer
  file: path={{ item }} state=absent
  with_items:
    - /etc/systemd/system/{{ rem_timer }}.service
    - /etc/systemd/system/{{ rem_timer }}.timer
  register: deleted

- systemd: daemon_reload=yes
  when: deleted.changed
