---
# We can't remove cronie without this
- name: Install cron dummy first so we don't get install loop
  aur: name=cron-dummy state=present
  become: yes
  become_user: makepkg

- name: Remove tools that are no longer used
  pacman: name={{ item }} state=absent
  with_items:
    - ctags
    - emojione-color-font
    - exfat-utils
    - lib32-apulse
    - ltrace
    - pdftk-bin
    - skype
    - ndenv
    - node-build
    - pkgfile
    - xf86-video-intel  # we always use KMS
    - openvpn-update-resolv-conf  # now managed by ansible directly
    - youtube-dl  # done through pyenv
    - frogr
    - wdiff
    - urlscan
    - xorg-xgamma
    - laptop-mode
    - docker
    - netatop-dkms
    - netatop
    - pandoc
    - gvfs-mtp
    - mtpfs
    - pandoc-lite  # old pandoc-bin
    - mcelog  # not in community or aur any more
    - cronie
    - lvm2
    - jfsutils
    - mdadm
    - nano
    - pcmciautils
    - reiserfsprogs
    - s-nail
    - xfsprogs

- name: Remove unused files
  file: path={{ item }} state=absent
  with_items:
    - /etc/udev/rules.d/99-deadline-for-ssd.rules
    - /etc/cron.d/clear-corrupt-journals
    - /etc/modprobe.d/99-i915.conf

- name: Remove old crons (now timers)
  file: path={{ item }} state=absent
  with_items:
    - /etc/cron.d/download-updates
    - /etc/cron.d/clean-cache
    - /etc/cron.d/fstrim
    - /etc/cron.d/i8kfan
    - /etc/cron.d/pkgfile
    - /etc/cron.d/purge-atop-logs
    - /etc/cron.d/reflector
