---
- name: Add snd_hda_intel power save settings
  copy: src=files/sound-power-save dest=/etc/modprobe.d/99-sound-power-save.conf mode=644
  when: model in ["T460s", "T470s", "X1 Carbon", "W530"]

- name: Install PulseAudio
  aur: name={{ item }}
  with_items:
    - pulseaudio
    - pulseaudio-ctl
  when: not minimal
  become: yes
  become_user: makepkg
