---
- name: Copy generate systemd-boot script
  copy: src=files/bin/generate-systemd-boot-config dest=/usr/local/bin/generate-systemd-boot-config mode=755

- name: Install intel-ucode
  pacman: name=intel-ucode state=present

- name: Install systemd-boot to /boot
  command: bootctl --path=/boot install
  changed_when: false

- name: Generate systemd-boot config
  command: "generate-systemd-boot-config {{ kernel }} '{{ default_kernel_params }} {{ extra_kernel_params }}'"
  register: gsc
  changed_when: false

- name: Copy systemd-boot config
  copy: 'content="{{ gsc.stdout }}\n" dest=/boot/loader/entries/arch.conf'

- name: Copy loader config
  copy: 'content="default arch\n" dest=/boot/loader/loader.conf'
